### ISSUE TITLE
leaks in font map

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#135]
Welcome to another episode of *Why I hate global variables* although this time the problem is more due to a lack of RAII (nonetheless I would like to get rid of as many globals as possible, possibly moving them to instantiate by library users explicitly).

Whenever I close any of examples which has some text, I'm getting *SPAMMED* with this and similar:

```
Indirect leak of 192 byte(s) in 6 object(s) allocated from:
    #0 0x7fbc79fc7f90 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xedf90)
    #1 0x7fbc78f958ed in FcStrSetCreate (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x218ed)
    #2 0x55564e0f315b in match /home/xeverous/workspace/elements/lib/src/support/font.cpp:221
    #3 0x55564e0f4baa in cycfi::elements::font::font(cycfi::elements::font_descr) /home/xeverous/workspace/elements/lib/src/support/font.cpp:292
    #4 0x55564e04f292 in cycfi::elements::theme::theme() /home/xeverous/workspace/elements/lib/src/support/theme.cpp:71
    #5 0x55564e0511b7 in cycfi::elements::global_theme::_theme() /home/xeverous/workspace/elements/lib/src/support/theme.cpp:78
    #6 0x55564e05121a in cycfi::elements::get_theme() /home/xeverous/workspace/elements/lib/src/support/theme.cpp:84
    #7 0x55564dfe84d8 in cycfi::elements::default_label::font_size() const (/home/xeverous/workspace/elements/build/examples/doc_aspects/Aspects+0x3b94d8)
    #8 0x55564e007af0 in cycfi::elements::default_label::limits(cycfi::elements::basic_context const&) const /home/xeverous/workspace/elements/lib/src/element/label.cpp:16
    #9 0x55564dff2588 in cycfi::elements::margin_element<cycfi::elements::rect, cycfi::elements::label_gen<cycfi::elements::basic_label_base<cycfi::elements::default_label> > >::limits(cycfi::elements::basic_context const&) const (/home/xeverous/workspace/elements/build/examples/doc_aspects/Aspects+0x3c3588)
    #10 0x55564e00ab88 in cycfi::elements::layer_element::limits(cycfi::elements::basic_context const&) const /home/xeverous/workspace/elements/lib/src/element/layer.cpp:20
    #11 0x55564e01d5cd in cycfi::elements::slider_base::limits(cycfi::elements::basic_context const&) const /home/xeverous/workspace/elements/lib/src/element/slider.cpp:16
    #12 0x55564dff2040 in cycfi::elements::halign_element<cycfi::elements::basic_slider<cycfi::elements::composite<std::array<std::shared_ptr<cycfi::elements::element>, 2ul>, cycfi::elements::layer_element>&, cycfi::elements::hsize_element<cycfi::elements::box_element>&, cycfi::elements::basic_slider_base> >::limits(cycfi::elements::basic_context const&) const (/home/xeverous/workspace/elements/build/examples/doc_aspects/Aspects+0x3c3040)
    #13 0x55564e00ab88 in cycfi::elements::layer_element::limits(cycfi::elements::basic_context const&) const /home/xeverous/workspace/elements/lib/src/element/layer.cpp:20
    #14 0x55564e0a0145 in cycfi::elements::indirect<cycfi::elements::reference<cycfi::elements::composite<std::vector<std::shared_ptr<cycfi::elements::element>, std::allocator<std::shared_ptr<cycfi::elements::element> > >, cycfi::elements::layer_element> > >::limits(cycfi::elements::basic_context const&) const (/home/xeverous/workspace/elements/build/examples/doc_aspects/Aspects+0x471145)
    #15 0x55564e08c507 in cycfi::elements::scale_element<cycfi::elements::indirect<cycfi::elements::reference<cycfi::elements::composite<std::vector<std::shared_ptr<cycfi::elements::element>, std::allocator<std::shared_ptr<cycfi::elements::element> > >, cycfi::elements::layer_element> > > >::limits(cycfi::elements::basic_context const&) const /home/xeverous/workspace/elements/lib/include/elements/element/size.hpp:608
    #16 0x55564e05b558 in cycfi::elements::view::set_limits() /home/xeverous/workspace/elements/lib/src/view.cpp:53
    #17 0x55564dfeac66 in void cycfi::elements::view::content<cycfi::elements::halign_element<cycfi::elements::basic_slider<cycfi::elements::composite<std::array<std::shared_ptr<cycfi::elements::element>, 2ul>, cycfi::elements::layer_element>&, cycfi::elements::hsize_element<cycfi::elements::box_element>&, cycfi::elements::basic_slider_base> >, cycfi::elements::box_element&>(cycfi::elements::halign_element<cycfi::elements::basic_slider<cycfi::elements::composite<std::array<std::shared_ptr<cycfi::elements::element>, 2ul>, cycfi::elements::layer_element>&, cycfi::elements::hsize_element<cycfi::elements::box_element>&, cycfi::elements::basic_slider_base> >&&, cycfi::elements::box_element&) (/home/xeverous/workspace/elements/build/examples/doc_aspects/Aspects+0x3bbc66)
    #18 0x55564dfe4d28 in main /home/xeverous/workspace/elements/examples/doc_aspects/main.cpp:96
    #19 0x7fbc7690bb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
```

```
SUMMARY: AddressSanitizer: 128202 byte(s) leaked in 4154 allocation(s).
```

`init_font_map()` is allocating some resources, but there is no counterpart. This function should be a member of come font-map-type constructor and have a respective destructor.

**Comment by djowel** [comment]
> `init_font_map()` is allocating some resources, but there is no counterpart. 

Seems like a font config issue: FcStrSetCreate. I do not know what global variables you are referring to. You should be more precise.

> This function should be a member of come font-map-type constructor and have a respective destructor.

The way you phrase it as "should be" seems to indicate that you already know the issue and solution, so why don't you just provide a PR instead?

**Comment by Xeverous** [comment]
> I do not know what global variables you are referring to. You should be more precise.

Not global in terms of visibility but it has global lifetime

https://github.com/cycfi/elements/blob/07acd87ffafead06050e2c5a5c2f4726b552573a/lib/src/support/font.cpp#L100-L104

> Seems like a font config issue: `FcStrSetCreate`.

I don't see any counterpart code for freeing fonts. Note that fontconfig library is absolutely full of function-macros (they even macro header names) so the symbols in sanitizers output may look different from actual code.

> The way you phrase it as "should be" seems to indicate that you already know the issue and solution, so why don't you just provide a PR instead?

Of course, wanted only to ask if there are any reasons for current implementation.

**Comment by djowel** [comment]
> I don't see any counterpart code for freeing fonts. Note that fontconfig library is absolutely full of function-macros (they even macro header names) so the symbols in sanitizers output may look different from actual code.

That will be destructed on program exit, obviously! :-) What is  `font_map_type`? It is `std::map`, which of course has its destructor. Think of it as sort of a cache. Unless you load 100s of fonts (unlikely and odd!), I do not see any reason for garbage collection mid stream.

**Comment by djowel** [comment]
I do not think that's the source of the leak. But prove me wrong.

**Comment by Xeverous** [comment]
> That will be destructed on program exit, obviously! :-)

True, but you know, I prefer not to have a thousands-line-long asan output when closing the program or redoing some init operations. I'm linking elements to other code to and would strongly prefer to have a clean tools output.

> What is `font_map_type`? It is `std::map`, which of course has its destructor.

Yes, the strings are destroyed. But font-config-allocated fonts are not. Font-config data is not RAII'd.

**Comment by djowel** [comment]
> Yes, the strings are destroyed. But font-config-allocated fonts are not. Font-config data is not RAII'd.

That is not correct. here's the full declaration of font_map_type:

```c++
      struct font_entry
      {
         std::string    full_name;
         std::string    file;
         uint8_t        weight   = font_constants::weight_normal;
         uint8_t        slant    = font_constants::slant_normal;
         uint8_t        stretch  = font_constants::stretch_normal;
      };

      using font_map_type = std::map<std::string, std::vector<font_entry>>;
```

**Comment by Xeverous** [comment]
> I do not think that's the source of the leak. But prove me wrong.

Want more sanitizer logs? :) There are so many of them...

```
Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fb363156f90 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xedf90)
    #1 0x7fb36211bfd6 in FcObjectSetBuild (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x18fd6)
    #2 0x56213a25477b in match /home/xeverous/workspace/elements/lib/src/support/font.cpp:221
    #3 0x56213a2561ca in cycfi::elements::font::font(cycfi::elements::font_descr) /home/xeverous/workspace/elements/lib/src/support/font.cpp:292
    #4 0x56213a2815dc in cycfi::elements::theme::theme() /home/xeverous/workspace/elements/lib/src/support/theme.cpp:71
    #5 0x56213a283501 in cycfi::elements::global_theme::_theme() /home/xeverous/workspace/elements/lib/src/support/theme.cpp:78
    #6 0x56213a283564 in cycfi::elements::get_theme() /home/xeverous/workspace/elements/lib/src/support/theme.cpp:84
    #7 0x56213a1fe1aa in operator() /home/xeverous/workspace/elements/examples/typography/main.cpp:19
    #8 0x56213a205417 in draw /home/xeverous/workspace/elements/lib/include/elements/element/misc.hpp:88
    #9 0x56213a31a473 in cycfi::elements::composite_base::draw(cycfi::elements::context const&) /home/xeverous/workspace/elements/lib/src/element/composite.cpp:44
    #10 0x56213a331e25 in cycfi::elements::layer_element::draw(cycfi::elements::context const&) /home/xeverous/workspace/elements/lib/src/element/layer.cpp:53
    #11 0x56213a2d3fab in cycfi::elements::indirect<cycfi::elements::reference<cycfi::elements::composite<std::vector<std::shared_ptr<cycfi::elements::element>, std::allocator<std::shared_ptr<cycfi::elements::element> > >, cycfi::elements::layer_element> > >::draw(cycfi::elements::context const&) (/home/xeverous/workspace/elements/build/examples/typography/Typography+0x4a0fab)
    #12 0x56213a33b32f in cycfi::elements::proxy_base::draw(cycfi::elements::context const&) /home/xeverous/workspace/elements/lib/src/element/proxy.cpp:38
    #13 0x56213a28ecd0 in cycfi::elements::view::draw(_cairo*, cycfi::elements::rect) /home/xeverous/workspace/elements/lib/src/view.cpp:94
    #14 0x56213a2fbfcc in on_draw /home/xeverous/workspace/elements/lib/host/linux/base_view.cpp:100
    #15 0x7fb3617788f6  (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0+0x2318f6)
```

>> Font-config data is not RAII'd.

> That is not correct.

So, what is the counterpart for `FcObjectSetBuild`? I don't see any `FcObjectSetDestroy` apart from the last line of `init_font_map` which destructs the font set when map initialization fails.

**Comment by djowel** [comment]
> So, what is the counterpart for `FcObjectSetBuild`? 

What I am saying is that you are barking at the wrong tree with the  `font_map()` global :-)

> I don't see any `FcObjectSetDestroy` apart from the last line of `init_font_map` 

Which does not have anything to do with ` font_map()` :-)

> which destructs the font set when map initialization fails.

I do not know what you mean.

**Comment by Xeverous** [comment]
Ok, I think that a PR will clearly express what I have in mind.

Said differently, the following function calls are reported by sanitizer which are on the border of elements/fontconfig call stack (and I haven't found their counterparts in elements source):

- `FcObjectSetBuild`
- `FcStrSetCreate`
- `FcFontSetCreate`
- maybe more (sanitizer output exceeds terminal buffer, haven't tried dumping it to a file yet)

**Comment by djowel** [comment]
> Said differently, the following function calls are reported by sanitizer which are on the border of elements/fontconfig call stack (and I haven't found their counterparts in elements source):
> 
> * `FcObjectSetBuild`
> * `FcStrSetCreate`
> * `FcFontSetCreate`
> * maybe more (sanitizer output exceeds terminal buffer, haven't tried dumping it to a file yet)

I think what started the confusion is that you initially pointed at the wrong code `font_map()` and claimed about the problem with "Welcome to another episode of Why I hate global variables", which is incorrect. 

I see now where the problem is, and it has nothing to do with `font_map()`, but rather some wrong usage of FontConfig, probably with unpaired Destroy calls.

**Comment by djowel** [comment]
Perhaps you should change the rhetoric to "Welcome to another episode of Why I hate C interfaces" :-) haha.

**Comment by Xeverous** [comment]
> Perhaps you should change the rhetoric to "Welcome to another episode of Why I hate C interfaces" :-) haha.

Right, this one is more appropriate for this issue. Especially "unRAII'd C interfaces". Whenever I see something like this (paired create+destroy calls) I immediately go for a rule of 5 class as this is the only way to guuarantee exception and scope safety. Even if there are no exceptions in surrounding code, having a destructor is much better than manually checking all the possible function execution paths.

**Comment by djowel** [comment]
> > Perhaps you should change the rhetoric to "Welcome to another episode of Why I hate C interfaces" :-) haha.
> 
> Right, this one is more appropriate for this issue. Especially "unRAII'd C interfaces". Whenever I see something like this (paired create+destroy calls) I immediately go for a rule of 5 class as this is the only way to guuarantee exception and scope safety. Even if there are no exceptions in surrounding code, having a destructor is much better than manually checking all the possible function execution paths.

That, I agree :-) PR welcome!!!

**Comment by Xeverous** [comment]
Time for actual issue of *Why I hate C interfaces*. On https://www.cairographics.org/manual/cairo-FreeType-Fonts.html#cairo-ft-font-face-create-for-ft-face there is a such line in a code snippet:

```c
status = cairo_font_face_set_user_data (font_face, &key,
                               ft_face, (cairo_destroy_func_t) FT_Done_Face);
```

This is intended to "append" a destructor to the cairo font face that will also free the freetype font face when cairo font face is no longer used. I obviously changed the C-style cast to `static_cast` in order to ensure nothing can go wrong.

And we get 2 surprises:

First, the code was relying on implicit function-to-function-pointer convertion:

```
lib/src/support/font.cpp: In member function ‘cairo_font_face_t* cycfi::elements::{anonymous}::free_type_library::load_font(const char*)’:
lib/src/support/font.cpp:337:117: error: invalid static_cast from type ‘FT_Error(FT_Face)’ {aka ‘int(FT_FaceRec_*)’} to type ‘cairo_destroy_func_t’ {aka ‘void (*)(void*)’}
                cairo_face, &cairo_user_data_key(), ft_face.release(), static_cast<cairo_destroy_func_t>(FT_Done_Face));
                                                                                                                     ^
```

So I add the `&` but the issue persists:

```
/lib/src/support/font.cpp: In member function ‘cairo_font_face_t* cycfi::elements::{anonymous}::free_type_library::load_font(const char*)’:
lib/src/support/font.cpp:337:118: error: invalid static_cast from type ‘FT_Error (*)(FT_Face)’ {aka ‘int (*)(FT_FaceRec_*)’} to type ‘cairo_destroy_func_t’ {aka ‘void (*)(void*)’}
                cairo_face, &cairo_user_data_key(), ft_face.release(), static_cast<cairo_destroy_func_t>(&FT_Done_Face));
                                                                                                                      ^
```

Now I see what's the real problem. The freetype function returns an `int` but the cairo destructor callback expects `void`. If I `reinterpet_cast` or C-style cast this thing, it would be undefined behavior to call it. I need to wrap `FT_Done_Face` in my own function that returns `void`.

...so by carefully not copy-pasting documentation examples I prevented from submiting a PR with UB.

**Comment by Xeverous** [comment]
See #138.

**Comment by jpcima** [comment]
Not sure if exactly related, but now I get a fontconfig-related crash on closing Ardour, after having opened my plugin UI.

```
ardour-6.0.0: fccache.c:768: FcCacheFini: Assertion `fcCacheChains[i] == NULL' failed.
```

**Comment by jpcima** [comment]
Yes visibily, it does not enjoy at all the call FcFini.
(because Ardour is a user of libfontconfig itself)

**Comment by Xeverous** [comment]
Can you bisect elements? Is 09898c1485ac1ff0aff5ae5a50cfb5add15c5040 the first bad commit?

**Comment by jpcima** [comment]
I'll be in trouble to bisect it because currently I have too much commits to make elements fit into my music plugin with Linux. I can just tell that removing `FcFini()` fixes it.

I makes sense, closing fontconfig as GTK uses it causes it to corrupt.
The solution is to leave Fontconfig open and let GTK do its thing.
I don't think It to be a big deal to leave it regardless the case; repetitions of `FcInit` calls don't accumulate memory leaks.

**Comment by Xeverous** [comment]
This is why I truly hate singletons. They just don't work in scenarios like this:

- code A uses S, initializing S's singleton
- code B uses S (without being aware what A is doing), thinking it is initializing S's singleton but in fact it was already done by A and the init done by B is a no-op
- code A destroys S
- code B crashes while it is still trying to use S

It's a lose-lose situation:

- Both A and B are correct within themselves, but can not work together. Leaving them as they are prevents from using them together. This is not good.
- Removing cleanup code is creating leaks. This is not good either.

2 libraries (here A and B) can not use the same library as their hidden, private dependency. At least not when the init+cleanup loop is coded as it is within fontconfig.

I see 4 ideal solutions to this problem:

- Reference counting: the problematic singleton should store a use count instead of a boolean state - each init increments it and each cleanup decrements it. I have already seen this in many C libraries. This solution requires S support.
- Separate instances 1: each user of the singleton has its own singleton. I'm not sure about your case, but it might be possible to achieve it by linking fontconfig statically into both A and B with no exported symbols. This is basically a build hack.
- Separate instances 2: for some libraries, they return some unique pointer/integer on each init call. This value might be required in various library functions. This allows to separate library instances to coexist in memory, similarly to the first solution. This also requires S support.
- Safe init+cleanup mechanism: some libraries do not require any explicit init and cleanup calls because they use platform-specific mechanism that is guuaranteed to work (eg callbacks that are invoked when a shared library is being loaded/unloaded). Requires S support.
- No singletons: no problem. I would like to remove all singletons in elements, so such problems are not present. If something requires global init, it should be forwarded upwards to the library users so they can dedice when/if they want to create an instance of it. In your case, you could use elements without initializing all of it's subdependencies through elements API because something else is already doing it.

**Comment by djowel** [comment]
> I don't think It to be a big deal to leave it regardless the case; repetitions of `FcInit` calls don't accumulate memory leaks.

Agreed! Let's not be too pedantic. It's not an ideal world. We have to deal with things like C :-)

**Comment by Xeverous** [comment]
Stuff like this (no cleanup after init) should be documented. I care about tooling support (eg sanitizers) and at least being able to safely "cleanup" dirty reports from tools about situations like this.

How about removing all singletons in elements? Move to some pattern like dependency injection. Example from my project to make it clear what I mean: I have a need to do logging. But I really, really hate global instances and singletons are just a glorified term for global variables. So instead of making a global logger instance, all functions which need logging take an extra logger parameter - they often are simpler wrappers that use logger-less functions inside. The logger is an abstract class. This lets me provide arbitrary instances (text file logger, stdout logger, UI rich text logger, string buffer logger, "/dev/null" black hole logger) for any code that needs it - it's especially useful for tests which 1) don't want to clutter stdout 2) want to output logs but only if test fails. There is no coupling between code and if there is a need for no logs, use log-less functions or supply a null logger.

**Comment by jpcima** [comment]
When examining sources of GTK and Pango, it shows fontconfig not to be closed by these libs.
Also there doesn't even seem to be a closing equivalent of `gtk_init`.

Also
- the trivial Qt app is also not valgrind clean
- the trivial fontconfig app `FcInit(); FcFini();` is not valgrind-clean

This really raises the question: are there any Linux graphical apps which are valgrind-clean?
and if there isn't, why would we have to be?

**Comment by Xeverous** [comment]
> This really raises the question: are there any Linux graphical apps which are valgrind-clean?
and if there isn't, why would we have to be?

Good question, but it raises the thought for me: "Why it has to be graphics"? What is causing the tolerance of the leaks in the community instead of focusing on better initialization/cleanup mechanisms such as simply counting the number of init calls?

**Comment by djowel** [comment]
This should be resolved now. Closing... Feel free to reopen if not.
