### ISSUE TITLE
linker fail after adding radio button

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#69]
104cef3cc19bf6f568b233a29679135a2c1f06ca - the commit before builds, but checkouting this gives me a linker error:

```
"C:\Program Files\CMake\bin\cmake.exe" -E remove -f CMakeFiles\EmptyStarter.dir/objects.a
C:\mingw64\mingw64\bin\gcc-ar.exe cr CMakeFiles\EmptyStarter.dir/objects.a @CMakeFiles\EmptyStarter.dir\objects1.rsp
C:\mingw64\mingw64\bin\g++.exe -O3 -DNDEBUG -flto -fno-fat-lto-objects  -mwindows -Wl,--whole-archive CMakeFiles\EmptyStarter.dir/objects.a -Wl,--no-whole-archive  -o D:\Files\C++\workspace_windows\filter_spirit\build\release\bin\EmptyStarter.exe -Wl,--out-implib,D:\Files\C++\workspace_windows\filter_spirit\build\release\bin\libEmptyStarter.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\EmptyStarter.dir\linklibs.rsp
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: radio_button.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn208_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): multiple definition of `cycfi::elements::basic_radio_button::~basic_radio_button()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn24_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: radio_button.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn208_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): multiple definition of `non-virtual thunk to cycfi::elements::basic_radio_button::~basic_radio_button()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn24_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: radio_button.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn208_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): multiple definition of `non-virtual thunk to cycfi::elements::basic_radio_button::~basic_radio_button()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn24_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
```

Checking what could cause the error, I'm basically gettting multiple definitions of some virtual tables and the `basic_radio_button` destructor.

Things I noted so far:

- There is no diamond inheritance problem.
- Currently I can not build anything past 104cef3cc19bf6f568b233a29679135a2c1f06ca, but yesterday I made a #68 PR and I actually build this one
- I'm getting a CMake warning about `INTERPROCEDURAL_OPTIMIZATION` property and policy 0069. Divergence in linker settings can actually create problems when LTO is (not) applied and some targets expects or do not expect certain symbols. GCC is known to have problems in some cases with targets with different linker flags.

**Comment by Xeverous** [comment]
This problems occurs for any example where I try to buid elements alone (witohut linking to any of my projects).

**Comment by djowel** [comment]
there is nothing special about 104cef3
have you tried clang?
did you do a git bisect?

**Comment by Xeverous** [comment]
I don't have any clang installation, but yes I did bisect commits untill I hit the one with radio button implementation. Commit before everything builds.

**Comment by Xeverous** [comment]
Anything common between these classes?

```
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: button.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements14layered_buttonD1Ev[_ZThn160_N5cycfi8elements14layered_buttonD1Ev]+0x0): multiple definition of `cycfi::elements::layered_button::~layered_button()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements14layered_buttonD1Ev[_ZThn24_N5cycfi8elements14layered_buttonD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: button.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements14layered_buttonD1Ev[_ZThn160_N5cycfi8elements14layered_buttonD1Ev]+0x0): multiple definition of `non-virtual thunk to cycfi::elements::layered_button::~layered_button()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements14layered_buttonD1Ev[_ZThn24_N5cycfi8elements14layered_buttonD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: button.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements14layered_buttonD1Ev[_ZThn160_N5cycfi8elements14layered_buttonD1Ev]+0x0): multiple definition of `non-virtual thunk to cycfi::elements::layered_button::~layered_button()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements14layered_buttonD1Ev[_ZThn24_N5cycfi8elements14layered_buttonD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: radio_button.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn208_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): multiple definition of `cycfi::elements::basic_radio_button::~basic_radio_button()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn24_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: radio_button.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn208_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): multiple definition of `non-virtual thunk to cycfi::elements::basic_radio_button::~basic_radio_button()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn24_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: radio_button.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn208_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): multiple definition of `non-virtual thunk to cycfi::elements::basic_radio_button::~basic_radio_button()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn24_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: radio_button.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn208_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): multiple definition of `non-virtual thunk to cycfi::elements::basic_radio_button::~basic_radio_button()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements18basic_radio_buttonD1Ev[_ZThn24_N5cycfi8elements18basic_radio_buttonD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: text.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements15basic_input_boxD1Ev[_ZThn32_N5cycfi8elements15basic_input_boxD1Ev]+0x0): multiple definition of `cycfi::elements::basic_input_box::~basic_input_box()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements15basic_input_boxD1Ev[_ZThn24_N5cycfi8elements15basic_input_boxD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: text.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements15basic_input_boxD1Ev[_ZThn32_N5cycfi8elements15basic_input_boxD1Ev]+0x0): multiple definition of `non-virtual thunk to cycfi::elements::basic_input_box::~basic_input_box()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements15basic_input_boxD1Ev[_ZThn24_N5cycfi8elements15basic_input_boxD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: text.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements15basic_input_boxD1Ev[_ZThn32_N5cycfi8elements15basic_input_boxD1Ev]+0x0): multiple definition of `non-virtual thunk to cycfi::elements::basic_input_box::~basic_input_box()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements15basic_input_boxD1Ev[_ZThn24_N5cycfi8elements15basic_input_boxD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: text.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements15static_text_boxD1Ev[_ZThn32_N5cycfi8elements15static_text_boxD1Ev]+0x0): multiple definition of `cycfi::elements::static_text_box::~static_text_box()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements15static_text_boxD1Ev[_ZThn24_N5cycfi8elements15static_text_boxD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: text.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements15static_text_boxD1Ev[_ZThn32_N5cycfi8elements15static_text_boxD1Ev]+0x0): multiple definition of `non-virtual thunk to cycfi::elements::static_text_box::~static_text_box()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements15static_text_boxD1Ev[_ZThn24_N5cycfi8elements15static_text_boxD1Ev]+0x0): first defined here
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: text.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements15static_text_boxD1Ev[_ZThn32_N5cycfi8elements15static_text_boxD1Ev]+0x0): multiple definition of `non-virtual thunk to cycfi::elements::static_text_box::~static_text_box()'; main.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN5cycfi8elements15static_text_boxD1Ev[_ZThn24_N5cycfi8elements15static_text_boxD1Ev]+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
```

**Comment by Xeverous** [comment]
I'm trying to bisect the commit itself to see what causes the build problem, so far this change repairs the build:

```diff
diff --git a/examples/buttons/main.cpp b/examples/buttons/main.cpp
index cfef8fa..f38786d 100755
--- a/examples/buttons/main.cpp
+++ b/examples/buttons/main.cpp
@@ -84,25 +84,6 @@ auto make_more_buttons()
             )
          );
 
-   auto  radio_button1 = radio_button("Eons from now");
-   auto  radio_button2 = radio_button("Ultra-sentient particles");
-   auto  radio_button3 = radio_button("The stratosphere is electrified");
-
-   radio_button1.select(true);
-
-   auto  group4 =
-         group("Radio Buttons",
-            margin({ 10, 10, 20, 20 },
-               top_margin(25,
-                  vtile(
-                     top_margin(10, align_left(radio_button1)),
-                     top_margin(10, align_left(radio_button2)),
-                     top_margin(10, align_left(radio_button3))
-                  )
-               )
-            )
-         );
-
    auto indicator_color = get_theme().indicator_color;
 
    auto  group2 =
@@ -145,7 +126,6 @@ auto make_more_buttons()
 
    return vtile(
       margin({ 20, 20, 20, 20 }, group1),
-      margin({ 20, 20, 20, 20 }, group4),
       margin({ 20, 20, 20, 20 }, group2),
       margin({ 20, 20, 20, 20 }, group3)
    );
diff --git a/lib/include/elements/element/gallery/radio_button.hpp b/lib/include/elements/element/gallery/radio_button.hpp
index 2c13ca0..caab36e 100644
--- a/lib/include/elements/element/gallery/radio_button.hpp
+++ b/lib/include/elements/element/gallery/radio_button.hpp
@@ -25,9 +25,11 @@ namespace cycfi { namespace elements
       element*          click(context const& ctx, mouse_button btn) override;
    };
 
-   void draw_radio_button(
+  inline void draw_radio_button(
       context const& ctx, std::string const& text, bool state, bool hilite
-   );
+   )
+  {
+  }
 
    template <bool state>
    struct radio_button_element : toggle_selector
diff --git a/lib/include/elements/element/selectable.hpp b/lib/include/elements/element/selectable.hpp
index 5fb8150..681993d 100755
--- a/lib/include/elements/element/selectable.hpp
+++ b/lib/include/elements/element/selectable.hpp
@@ -39,4 +39,4 @@ namespace cycfi { namespace elements
    }
 }}
 
-#endif
\ No newline at end of file
+#endif
diff --git a/lib/include/elements/support/circle.hpp b/lib/include/elements/support/circle.hpp
index 7c4cdab..34725c8 100755
--- a/lib/include/elements/support/circle.hpp
+++ b/lib/include/elements/support/circle.hpp
@@ -7,7 +7,6 @@
 #define ELEMENTS_CIRCLE_APRIL_17_2016
 
 #include <elements/support/rect.hpp>
-#include <algorithm>
 
 namespace cycfi { namespace elements
 {
@@ -19,7 +18,6 @@ namespace cycfi { namespace elements
       constexpr   circle();
       constexpr   circle(float cx, float cy, float radius);
       constexpr   circle(point c, float radius);
-      constexpr   circle(rect r);
                   circle(circle const&) = default;
       circle&     operator=(circle const&) = default;
 
@@ -52,10 +50,6 @@ namespace cycfi { namespace elements
     : cx(c.x), cy(c.y), radius(radius)
    {}
 
-   inline constexpr circle::circle(rect r)
-    : circle(center_point(r), std::min(r.width(), r.height()))
-   {}
-
    inline bool circle::operator==(circle const& other) const
    {
       return (other.cx == cx) && (other.cy == cy) && (other.radius == radius);
diff --git a/lib/src/element/gallery/radio_button.cpp b/lib/src/element/gallery/radio_button.cpp
index 87538ae..5bf8e26 100644
--- a/lib/src/element/gallery/radio_button.cpp
+++ b/lib/src/element/gallery/radio_button.cpp
@@ -7,54 +7,6 @@
 
 namespace cycfi { namespace elements
 {
-   void draw_radio_button(
-     context const& ctx, std::string const& text, bool state, bool hilite
-   )
-   {
-      auto&       canvas_ = ctx.canvas;
-      auto        canvas_state = canvas_.new_state();
-      auto const& theme_ = get_theme();
-      color const indicator_color = theme_.indicator_color;
-      float const bg_alfa = theme_.box_widget_bg_opacity;
-      rect        box = ctx.bounds.move(15, 0);
-      float       size = box.height();
-      float       radius = size/2;
-      float       dot_radius = radius/2.5;
-
-      box.width(size);
-      point       center = center_point(box);
-
-      color c1 = state ? indicator_color.level(1.5) : rgb(0, 0, 0).opacity(bg_alfa);
-
-      if (state)
-      {
-         canvas_.begin_path();
-         canvas_.fill_style(c1.level(hilite ? 2.0 : 1.0));
-         canvas_.circle(circle(center, dot_radius));
-         canvas_.fill();
-      }
-
-      color outline_color = theme_.frame_color;
-      canvas_.begin_path();
-      canvas_.circle(circle(center, radius-1));
-      canvas_.stroke_style(outline_color);
-      canvas_.stroke();
-
-      // Pseudo glow
-      canvas_.circle(circle(center, radius));
-      canvas_.stroke_style(outline_color.opacity(0.1));
-      canvas_.stroke();
-
-      canvas_.fill_style(theme_.label_font_color);
-      canvas_.font(
-         theme_.label_font,
-         theme_.label_font_size
-      );
-      canvas_.text_align(canvas_.left | canvas_.middle);
-      float cx = box.right + 10;
-      float cy = ctx.bounds.top + (ctx.bounds.height() / 2);
-      canvas_.fill_text(point{ cx, cy }, text.c_str());
-   }
 
    void basic_radio_button::select(bool state)
    {
```

**Comment by Xeverous** [comment]
Adding the code to `examples/button/main.cpp` causes this example to fail to build. Looks like a compiler/linker bug or CMake flags problem. So far solutions from Stack Overflow did not help.

**Comment by djowel** [comment]
Looks like a compiler bug to me

**Comment by Xeverous** [comment]
https://github.com/cycfi/elements/blob/9aa5d3cda37558a0279aafb15ad945f9b66af5e6/lib/include/elements/element/receiver.hpp#L11-L22

This type has a virtual method but non-virtual destructor. Also, there is a specialization for `std::string` that missed its include.

Addind virtual dtor does not help in my problem but it still is worth to do.

**Comment by djowel** [comment]
> This type has a virtual method but non-virtual destructor. Also, there is a specialization for `std::string` that missed its include.

Good catch!

**Comment by djowel** [comment]
> Anything common between these classes?

Nothing stands out really... I'll check on linux if i get the same linker problem

**Comment by djowel** [comment]
> Nothing stands out really... I'll check on linux if i get the same linker problem

Builds and runs fine on Linux. It seems like it's mingw64 thing only.

**Comment by Xeverous** [comment]
What is your GCC version? Mine is 9.2.1 and GNU ld 2.33.1

**Comment by djowel** [comment]
> Builds and runs fine on Linux. It seems like it's mingw64 thing only.

No problem with Visual studio as well. But please try pulling the latest develop. I added your fix to receiver and another potential multi-inheritance issue with text_base.

**Comment by djowel** [comment]
> What is your GCC version? Mine is 9.2.1 and GNU ld 2.33.1

g++ (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

**Comment by Xeverous** [comment]
Now I get even more multiple definition linker errors.

This problem is only present when building elements as a static library, shared lib build works.

**Comment by djowel** [comment]
> This problem is only present when building elements as a static library, shared lib build works.

Odd. really odd. FWIW, Linux, MacOS and Visual Studio builds and runs just fine both before and after.

**Comment by Xeverous** [comment]
The fun begins now: used an older GCC installation on an office PC and it does build

GCC 8.3.1 GNU ld 2.30

**Comment by Xeverous** [comment]
Nevermind, actually my fault - old GCC was building in debug. The old one in release also has the linke error.

**Comment by djowel** [comment]
> Nevermind, actually my fault - old GCC was building in debug. The old one in release also has the linke error.

Oh, does it happen only in release? I should check that! I didn't know.

**Comment by Xeverous** [comment]
See https://stackoverflow.com/q/60591742/4818802 for more details

**Comment by djowel** [comment]
> Oh, does it happen only in release? I should check that! I didn't know.

Nope. No problem in Linux in release mode.

**Comment by djowel** [comment]
> See https://stackoverflow.com/q/60591742/4818802 for more details

"LTO is generally non-functional for MinGW targets due to issues like this. I would save yourself the trouble and disable it. "

Have you tried disabling LTO?

**Comment by djowel** [comment]
> Have you tried disabling LTO?

Of course you did :-) "The problem does not occur when LTO is not enabled" Sorry...

**Comment by Xeverous** [comment]
Yes, the issue appears only for classes with multiple inheritance, only with LTO, only in Release only in static library build.

**Comment by djowel** [comment]
> Yes, the issue appears only for classes with multiple inheritance, only with LTO, only in Release only in static library build.

And only with MinGW. Linux is fine.

**Comment by Xeverous** [comment]
Closing this as it is not an elements issue, I have 1 more idea how to try to reproduce it on a smaller example but there is no simple workaround other than just disabling LTO (unless you can and are willing to refactor all multi-inheritance classes to use single inheritance - only multiple inheriting classes are affected). I will do so then to just stop losing time on the problem and move forward - planning to be a bit busy in the upcoming weeks on other things although my work seems to have more free time soon.

**Comment by Xeverous** [comment]
We will see where it goes: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94156
